name: Keep Streamlit Awake

on:
  schedule:
    - cron: "0 */10 * * *" # Runs automatically every 10 hours
  workflow_dispatch: # Allows you to trigger it manually if needed

jobs:
  keep-alive:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4
      - name: Keep alive with empty commit
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git commit --allow-empty -m "chore: keep streamlit app awake"
          git push
